repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/prospector
    rev: master # The version of Prospector to use, at least 1.1.7
    hooks:
    -   id: prospector